// This file was generated by Rainbow for .NET Core. Do not modify.
//
// Copyright (c) 2010-present Bifrost Entertainment AS and Tommy Nguyen
// Distributed under the MIT License.
// (See accompanying file LICENSE or copy at http://opensource.org/licenses/MIT)

namespace Rainbow.Graphics
{
    using System;

    using Interop;

    /// <content>
    /// Contains unmanaged delegates for <see cref="FontAtlas"/>.
    /// </content>
    public sealed partial class FontAtlas : NativeObject<FontAtlas>
    {
        private static FuncCFP ctor;
        private static MemberFuncI getHeight;
        private static MemberFuncB isValid;

        internal static void InitializeComponents(IntPtr ptr)
        {
            var ftable = InitializeComponents<UFontAtlas>(ptr);
            GetDelegateForFunctionPointer(ftable.CtorFunc, out ctor);
            GetDelegateForFunctionPointer(ftable.GetHeightFunc, out getHeight);
            GetDelegateForFunctionPointer(ftable.IsValidFunc, out isValid);
        }
    }
}
