// This file was generated by Rainbow for .NET Core. Do not modify.
//
// Copyright (c) 2010-present Bifrost Entertainment AS and Tommy Nguyen
// Distributed under the MIT License.
// (See accompanying file LICENSE or copy at http://opensource.org/licenses/MIT)

namespace Rainbow.Graphics
{
    using System;

    using Interop;

    /// <content>
    /// Contains unmanaged delegates for <see cref="Label"/>.
    /// </content>
    public sealed partial class Label : NativeObject<Label>
    {
        private static FuncP ctor;
        private static MemberFuncI getAlignment;
        private static MemberFuncF getAngle;
        private static MemberFuncCo getColor;
        private static MemberFuncV getPosition;
        private static MemberFuncF getScale;
        private static MemberFuncI getWidth;
        private static MemberActionCo setColor;
        private static MemberActionP setFont;
        private static MemberActionI setAlignment;
        private static MemberActionV setPosition;
        private static MemberActionF setRotation;
        private static MemberActionF setScale;
        private static MemberActionC setText;

        internal static void InitializeComponents(IntPtr ptr)
        {
            var ftable = InitializeComponents<ULabel>(ptr);
            GetDelegateForFunctionPointer(ftable.CtorFunc, out ctor);
            GetDelegateForFunctionPointer(ftable.GetAlignmentFunc, out getAlignment);
            GetDelegateForFunctionPointer(ftable.GetAngleFunc, out getAngle);
            GetDelegateForFunctionPointer(ftable.GetColorFunc, out getColor);
            GetDelegateForFunctionPointer(ftable.GetPositionFunc, out getPosition);
            GetDelegateForFunctionPointer(ftable.GetScaleFunc, out getScale);
            GetDelegateForFunctionPointer(ftable.GetWidthFunc, out getWidth);
            GetDelegateForFunctionPointer(ftable.SetColorFunc, out setColor);
            GetDelegateForFunctionPointer(ftable.SetFontFunc, out setFont);
            GetDelegateForFunctionPointer(ftable.SetAlignmentFunc, out setAlignment);
            GetDelegateForFunctionPointer(ftable.SetPositionFunc, out setPosition);
            GetDelegateForFunctionPointer(ftable.SetRotationFunc, out setRotation);
            GetDelegateForFunctionPointer(ftable.SetScaleFunc, out setScale);
            GetDelegateForFunctionPointer(ftable.SetTextFunc, out setText);
        }
    }
}
