coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
  ignore:
    - build/.*
    - lib/.*
    - src/Graphics/Shaders.*
    - src/Resources/.*
    - src/Script/JavaScript/Modules.g.h
    - src/Tests/.*
