path_classifiers:
  generated:
    - "**/*.g.*"
  library:
    - lib
  test:
    - "**/*.test.cc"
extraction:
  cpp:
    prepare:
      packages:
        - libpulse-dev
        - libsdl2-dev
        - ninja-build
        - pkg-config
        - pulseaudio
    configure:
      command:
        - mkdir out
        - cd out
        - cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_PHYSICS=1 -G Ninja ..
    index:
      build_command:
        - cd out
        - ninja
