// This file was generated by Rainbow for .NET Core. Do not modify.
//
// Copyright (c) 2010-present Bifrost Entertainment AS and Tommy Nguyen
// Distributed under the MIT License.
// (See accompanying file LICENSE or copy at http://opensource.org/licenses/MIT)

namespace Rainbow.Audio
{
    using System;

    using Interop;

    /// <content>
    /// Contains unmanaged delegates for <see cref="Sound"/>.
    /// </content>
    public sealed partial class Sound : NativeObject<Sound>
    {
        internal static void InitializeComponents(IntPtr ptr)
        {
            var ftable = InitializeComponents<USound>(ptr);
        }
    }
}
