// This file was generated by `generate-shaders.ts`. DO NOT MODIFY!
//
// Copyright (c) 2010-present Bifrost Entertainment AS and Tommy Nguyen
// Distributed under the MIT License.
// (See accompanying file LICENSE or copy at http://opensource.org/licenses/MIT)

#include "Graphics/ShaderDetails.h"

namespace rainbow::gl
{
    auto DiffuseLight2D_frag() -> Shader::Params;
    auto DiffuseLightNormal_frag() -> Shader::Params;
    auto Fixed2D_frag() -> Shader::Params;
    auto Fixed2D_vert() -> Shader::Params;
    auto NormalMapped_vert() -> Shader::Params;
    auto Simple_frag() -> Shader::Params;
    auto Simple2D_vert() -> Shader::Params;
}  // namespace rainbow::gl
