// This file was generated by Rainbow for .NET Core. Do not modify.
//
// Copyright (c) 2010-present Bifrost Entertainment AS and Tommy Nguyen
// Distributed under the MIT License.
// (See accompanying file LICENSE or copy at http://opensource.org/licenses/MIT)

#ifndef DOTNET_RAINBOW_INTEROP_UMASTER_H_
#define DOTNET_RAINBOW_INTEROP_UMASTER_H_

#include "DotNet/Rainbow/Interop/Audio/UMixer.h"
#include "DotNet/Rainbow/Interop/Audio/USound.h"
#include "DotNet/Rainbow/Interop/Graphics/UAnimation.h"
#include "DotNet/Rainbow/Interop/Graphics/UFontAtlas.h"
#include "DotNet/Rainbow/Interop/Graphics/ULabel.h"
#include "DotNet/Rainbow/Interop/Graphics/URenderQueue.h"
#include "DotNet/Rainbow/Interop/Graphics/USprite.h"
#include "DotNet/Rainbow/Interop/Graphics/USpriteBatch.h"
#include "DotNet/Rainbow/Interop/Graphics/UTextureAtlas.h"

namespace rainbow
{
    struct UMaster
    {
        uint32_t size_of_struct = sizeof(UMaster);
        graphics::RenderQueue* render_queue_instance;
        UMixer* mixer;
        USound* sound;
        UAnimation* animation;
        UFontAtlas* font_atlas;
        ULabel* label;
        URenderQueue* render_queue;
        USprite* sprite;
        USpriteBatch* sprite_batch;
        UTextureAtlas* texture_atlas;
    };

    void initialize_components(graphics::RenderQueue& render_queue_instance,
                               void (*initialize_components)(void*))
    {
        UMixer mixer;
        USound sound;
        UAnimation animation;
        UFontAtlas font_atlas;
        ULabel label;
        URenderQueue render_queue;
        USprite sprite;
        USpriteBatch sprite_batch;
        UTextureAtlas texture_atlas;

        UMaster master;
        master.render_queue_instance = &render_queue_instance;
        master.mixer = &mixer;
        master.sound = &sound;
        master.animation = &animation;
        master.font_atlas = &font_atlas;
        master.label = &label;
        master.render_queue = &render_queue;
        master.sprite = &sprite;
        master.sprite_batch = &sprite_batch;
        master.texture_atlas = &texture_atlas;

        initialize_components(&master);
    }
}

#endif
