// This file was generated by Rainbow for .NET Core. Do not modify.
//
// Copyright (c) 2010-present Bifrost Entertainment AS and Tommy Nguyen
// Distributed under the MIT License.
// (See accompanying file LICENSE or copy at http://opensource.org/licenses/MIT)

namespace Rainbow.Interop
{
    using System;
    using System.Runtime.InteropServices;

    [StructLayout(LayoutKind.Sequential)]
    internal sealed class UMaster
    {
        private readonly uint sizeOfStruct;
        private readonly IntPtr renderQueueInstance;
        private readonly IntPtr mixer;
        private readonly IntPtr sound;
        private readonly IntPtr animation;
        private readonly IntPtr fontAtlas;
        private readonly IntPtr label;
        private readonly IntPtr renderQueue;
        private readonly IntPtr sprite;
        private readonly IntPtr spriteBatch;
        private readonly IntPtr textureAtlas;

        public uint SizeOfStruct => sizeOfStruct;

        public IntPtr RenderQueueInstance => renderQueueInstance;

        public IntPtr Mixer => mixer;

        public IntPtr Sound => sound;

        public IntPtr Animation => animation;

        public IntPtr FontAtlas => fontAtlas;

        public IntPtr Label => label;

        public IntPtr RenderQueue => renderQueue;

        public IntPtr Sprite => sprite;

        public IntPtr SpriteBatch => spriteBatch;

        public IntPtr TextureAtlas => textureAtlas;
    }
}
