// This file was generated by Rainbow for .NET Core. Do not modify.
//
// Copyright (c) 2010-present Bifrost Entertainment AS and Tommy Nguyen
// Distributed under the MIT License.
// (See accompanying file LICENSE or copy at http://opensource.org/licenses/MIT)

namespace Rainbow.Interop
{
    using System;

    using Graphics;

    public unsafe delegate void ActionPF(IntPtr a, float b);

    public unsafe delegate void ActionPI(IntPtr a, int b);

    public unsafe delegate void ActionPV(IntPtr a, Vector2 b);

    public unsafe delegate void ActionP(IntPtr a);

    public unsafe delegate IntPtr FuncCFP(byte[] a, float b);

    public unsafe delegate IntPtr FuncCP(byte[] a);

    public unsafe delegate IntPtr FuncP();

    public unsafe delegate bool FuncPB(IntPtr a);

    public unsafe delegate IntPtr FuncPP(IntPtr a);

    public unsafe delegate IntPtr FuncPUUpUUIP(IntPtr a, uint b, uint[] c, uint d, uint e, int f);

    public unsafe delegate IntPtr FuncPVP(IntPtr a, Vector2 b);

    public unsafe delegate IntPtr FuncUP(uint a);

    public unsafe delegate void MemberActionB(IntPtr a, bool b);

    public unsafe delegate void MemberActionC(IntPtr a, byte[] b);

    public unsafe delegate void MemberActionCo(IntPtr a, Color b);

    public unsafe delegate void MemberActionF(IntPtr a, float b);

    public unsafe delegate void MemberActionIC(IntPtr a, int b, byte[] c);

    public unsafe delegate void MemberActionI(IntPtr a, int b);

    public unsafe delegate void MemberActionIpI(IntPtr a, int[] b, int c);

    public unsafe delegate void MemberActionPU(IntPtr a, IntPtr b, uint c);

    public unsafe delegate void MemberActionP(IntPtr a, IntPtr b);

    public unsafe delegate void MemberActionUB(IntPtr a, uint b, bool c);

    public unsafe delegate void MemberActionUCo(IntPtr a, uint b, Color c);

    public unsafe delegate void MemberActionUF(IntPtr a, uint b, float c);

    public unsafe delegate void MemberActionUI(IntPtr a, uint b, int c);

    public unsafe delegate void MemberActionUU(IntPtr a, uint b, uint c);

    public unsafe delegate void MemberActionUV(IntPtr a, uint b, Vector2 c);

    public unsafe delegate void MemberActionU(IntPtr a, uint b);

    public unsafe delegate void MemberActionUpU(IntPtr a, uint[] b, uint c);

    public unsafe delegate void MemberActionV(IntPtr a, Vector2 b);

    public unsafe delegate void MemberAction(IntPtr a);

    public unsafe delegate bool MemberFuncB(IntPtr a);

    public unsafe delegate Color MemberFuncCo(IntPtr a);

    public unsafe delegate float MemberFuncF(IntPtr a);

    public unsafe delegate int MemberFuncI(IntPtr a);

    public unsafe delegate uint MemberFuncIIIIU(IntPtr a, int b, int c, int d, int e);

    public unsafe delegate int MemberFuncIPCI(IntPtr a, int b, IntPtr c, byte[] d);

    public unsafe delegate uint MemberFuncIU(IntPtr a, int b);

    public unsafe delegate int MemberFuncPCI(IntPtr a, IntPtr b, byte[] c);

    public unsafe delegate uint MemberFuncU(IntPtr a);

    public unsafe delegate bool MemberFuncUB(IntPtr a, uint b);

    public unsafe delegate Color MemberFuncUCo(IntPtr a, uint b);

    public unsafe delegate float MemberFuncUF(IntPtr a, uint b);

    public unsafe delegate int MemberFuncUI(IntPtr a, uint b);

    public unsafe delegate uint MemberFuncUU(IntPtr a, uint b);

    public unsafe delegate uint MemberFuncUUU(IntPtr a, uint b, uint c);

    public unsafe delegate Vector2 MemberFuncUV(IntPtr a, uint b);

    public unsafe delegate Vector2 MemberFuncV(IntPtr a);
}
