// This file was generated by Rainbow for .NET Core. Do not modify.
//
// Copyright (c) 2010-present Bifrost Entertainment AS and Tommy Nguyen
// Distributed under the MIT License.
// (See accompanying file LICENSE or copy at http://opensource.org/licenses/MIT)

namespace Rainbow.Interop
{
    using System;
    using System.Runtime.InteropServices;

    [StructLayout(LayoutKind.Sequential)]
    internal sealed class URenderQueue : ITable
    {
        private readonly uint sizeOfStruct;
        private readonly IntPtr dtorFunc;
        private readonly IntPtr addAnimationFunc;
        private readonly IntPtr addLabelFunc;
        private readonly IntPtr addSpritebatchFunc;
        private readonly IntPtr clearFunc;
        private readonly IntPtr disableFunc;
        private readonly IntPtr disableTagFunc;
        private readonly IntPtr enableFunc;
        private readonly IntPtr enableTagFunc;
        private readonly IntPtr insertAnimationFunc;
        private readonly IntPtr insertLabelFunc;
        private readonly IntPtr insertSpritebatchFunc;
        private readonly IntPtr removeAtFunc;
        private readonly IntPtr removeFunc;
        private readonly IntPtr setTagFunc;

        public uint SizeOfStruct => sizeOfStruct;

        public IntPtr DtorFunc => dtorFunc;

        public IntPtr AddAnimationFunc => addAnimationFunc;

        public IntPtr AddLabelFunc => addLabelFunc;

        public IntPtr AddSpritebatchFunc => addSpritebatchFunc;

        public IntPtr ClearFunc => clearFunc;

        public IntPtr DisableFunc => disableFunc;

        public IntPtr DisableTagFunc => disableTagFunc;

        public IntPtr EnableFunc => enableFunc;

        public IntPtr EnableTagFunc => enableTagFunc;

        public IntPtr InsertAnimationFunc => insertAnimationFunc;

        public IntPtr InsertLabelFunc => insertLabelFunc;

        public IntPtr InsertSpritebatchFunc => insertSpritebatchFunc;

        public IntPtr RemoveAtFunc => removeAtFunc;

        public IntPtr RemoveFunc => removeFunc;

        public IntPtr SetTagFunc => setTagFunc;
    }
}
