// This file was generated by Rainbow for .NET Core. Do not modify.
//
// Copyright (c) 2010-present Bifrost Entertainment AS and Tommy Nguyen
// Distributed under the MIT License.
// (See accompanying file LICENSE or copy at http://opensource.org/licenses/MIT)

namespace Rainbow.Interop
{
    using System;
    using System.Runtime.InteropServices;

    [StructLayout(LayoutKind.Sequential)]
    internal sealed class USound : ITable
    {
        private readonly uint sizeOfStruct;
        private readonly IntPtr dtorFunc;

        public uint SizeOfStruct => sizeOfStruct;

        public IntPtr DtorFunc => dtorFunc;
    }
}
