// This file was generated by Rainbow for .NET Core. Do not modify.
//
// Copyright (c) 2010-present Bifrost Entertainment AS and Tommy Nguyen
// Distributed under the MIT License.
// (See accompanying file LICENSE or copy at http://opensource.org/licenses/MIT)

namespace Rainbow.Interop
{
    using System;
    using System.Runtime.InteropServices;

    [StructLayout(LayoutKind.Sequential)]
    internal sealed class USprite : ITable
    {
        private readonly uint sizeOfStruct;
        private readonly IntPtr dtorFunc;
        private readonly IntPtr getAngleFunc;
        private readonly IntPtr getColorFunc;
        private readonly IntPtr getHeightFunc;
        private readonly IntPtr getIdFunc;
        private readonly IntPtr isFlippedFunc;
        private readonly IntPtr isHiddenFunc;
        private readonly IntPtr isMirroredFunc;
        private readonly IntPtr getPivotFunc;
        private readonly IntPtr getPositionFunc;
        private readonly IntPtr getScaleFunc;
        private readonly IntPtr getWidthFunc;
        private readonly IntPtr setColorFunc;
        private readonly IntPtr setFlippedFunc;
        private readonly IntPtr setIdFunc;
        private readonly IntPtr setMirroredFunc;
        private readonly IntPtr setNormalFunc;
        private readonly IntPtr setPivotFunc;
        private readonly IntPtr setPositionFunc;
        private readonly IntPtr setRotationFunc;
        private readonly IntPtr setScaleFunc;
        private readonly IntPtr setTextureFunc;
        private readonly IntPtr hideFunc;
        private readonly IntPtr showFunc;

        public uint SizeOfStruct => sizeOfStruct;

        public IntPtr DtorFunc => dtorFunc;

        public IntPtr GetAngleFunc => getAngleFunc;

        public IntPtr GetColorFunc => getColorFunc;

        public IntPtr GetHeightFunc => getHeightFunc;

        public IntPtr GetIdFunc => getIdFunc;

        public IntPtr IsFlippedFunc => isFlippedFunc;

        public IntPtr IsHiddenFunc => isHiddenFunc;

        public IntPtr IsMirroredFunc => isMirroredFunc;

        public IntPtr GetPivotFunc => getPivotFunc;

        public IntPtr GetPositionFunc => getPositionFunc;

        public IntPtr GetScaleFunc => getScaleFunc;

        public IntPtr GetWidthFunc => getWidthFunc;

        public IntPtr SetColorFunc => setColorFunc;

        public IntPtr SetFlippedFunc => setFlippedFunc;

        public IntPtr SetIdFunc => setIdFunc;

        public IntPtr SetMirroredFunc => setMirroredFunc;

        public IntPtr SetNormalFunc => setNormalFunc;

        public IntPtr SetPivotFunc => setPivotFunc;

        public IntPtr SetPositionFunc => setPositionFunc;

        public IntPtr SetRotationFunc => setRotationFunc;

        public IntPtr SetScaleFunc => setScaleFunc;

        public IntPtr SetTextureFunc => setTextureFunc;

        public IntPtr HideFunc => hideFunc;

        public IntPtr ShowFunc => showFunc;
    }
}
