// This file was generated by Rainbow for .NET Core. Do not modify.
//
// Copyright (c) 2010-present Bifrost Entertainment AS and Tommy Nguyen
// Distributed under the MIT License.
// (See accompanying file LICENSE or copy at http://opensource.org/licenses/MIT)

namespace Rainbow.Interop
{
    using System;
    using System.Runtime.InteropServices;

    [StructLayout(LayoutKind.Sequential)]
    internal sealed class USpriteBatch : ITable
    {
        private readonly uint sizeOfStruct;
        private readonly IntPtr ctorFunc;
        private readonly IntPtr dtorFunc;
        private readonly IntPtr countFunc;
        private readonly IntPtr isVisibleFunc;
        private readonly IntPtr setNormalFunc;
        private readonly IntPtr setTextureFunc;
        private readonly IntPtr setVisibleFunc;
        private readonly IntPtr bringToFrontFunc;
        private readonly IntPtr clearFunc;
        private readonly IntPtr createSpriteFunc;
        private readonly IntPtr eraseFunc;
        private readonly IntPtr findSpriteByIdFunc;
        private readonly IntPtr moveFunc;
        private readonly IntPtr swapFunc;

        public uint SizeOfStruct => sizeOfStruct;

        public IntPtr CtorFunc => ctorFunc;

        public IntPtr DtorFunc => dtorFunc;

        public IntPtr CountFunc => countFunc;

        public IntPtr IsVisibleFunc => isVisibleFunc;

        public IntPtr SetNormalFunc => setNormalFunc;

        public IntPtr SetTextureFunc => setTextureFunc;

        public IntPtr SetVisibleFunc => setVisibleFunc;

        public IntPtr BringToFrontFunc => bringToFrontFunc;

        public IntPtr ClearFunc => clearFunc;

        public IntPtr CreateSpriteFunc => createSpriteFunc;

        public IntPtr EraseFunc => eraseFunc;

        public IntPtr FindSpriteByIdFunc => findSpriteByIdFunc;

        public IntPtr MoveFunc => moveFunc;

        public IntPtr SwapFunc => swapFunc;
    }
}
