// This file was generated by Rainbow for .NET Core. Do not modify.
//
// Copyright (c) 2010-present Bifrost Entertainment AS and Tommy Nguyen
// Distributed under the MIT License.
// (See accompanying file LICENSE or copy at http://opensource.org/licenses/MIT)

namespace Rainbow.Interop
{
    using System;
    using System.Runtime.InteropServices;

    [StructLayout(LayoutKind.Sequential)]
    internal sealed class UTextureAtlas : ITable
    {
        private readonly uint sizeOfStruct;
        private readonly IntPtr ctorFunc;
        private readonly IntPtr dtorFunc;
        private readonly IntPtr getHeightFunc;
        private readonly IntPtr getWidthFunc;
        private readonly IntPtr isValidFunc;
        private readonly IntPtr addRegionFunc;
        private readonly IntPtr getTextureRegionFunc;
        private readonly IntPtr setRegionsFunc;

        public uint SizeOfStruct => sizeOfStruct;

        public IntPtr CtorFunc => ctorFunc;

        public IntPtr DtorFunc => dtorFunc;

        public IntPtr GetHeightFunc => getHeightFunc;

        public IntPtr GetWidthFunc => getWidthFunc;

        public IntPtr IsValidFunc => isValidFunc;

        public IntPtr AddRegionFunc => addRegionFunc;

        public IntPtr GetTextureRegionFunc => getTextureRegionFunc;

        public IntPtr SetRegionsFunc => setRegionsFunc;
    }
}
